# Generated by Django 4.2.6 on 2023-10-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='auth_user',
        ),
    ]
