# Generated by Django 4.2.6 on 2023-11-04 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_emailing_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ManyToManyField(related_name='messages', to='main.client', verbose_name='Клиент'),
        ),
    ]
